apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rs
  labels:
    app: nginx
    demo: deployment
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      demo: deployment
  template: # pod defination
    metadata:
      labels:
        app: nginx
        demo: deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
