apiVersion: v1
kind: Pod
metadata: 
  name: secrete-pod-1
spec:
  containers:
  - name: secrete-pod-1
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: devops-secret